Repository hmcts/et-pet-api, pull requests merged in 2024-11, with the labels that each got.

#717 upgrade ruby version by changing .ruby-version & Dockerfile
  .bundler-audit.yml
  .ruby-version
  Dockerfile
  Gemfile.lock
Labels: ns:et-pet, prd:et-pet, rel:et-pet-api-pr-717

#722 (RST-6972) - Reform office allocation now only on specific external systems
  Gemfile
  Gemfile.lock
  app/event_handlers/response_assign_office_handler.rb
  app/event_handlers/response_export_feedback_received_handler.rb
  app/event_handlers/response_export_handler.rb
  config/initializers/event_handlers.rb
  db/migrate/20241115063248_add_response_remote_office_to_external_systems.rb
  db/migrate/20241115064151_set_ccd_england_and_wales_to_use_response_remote_office.rb
  db/schema.rb
  db/seeds.rb
  spec/event_handlers/response_export_feedback_received_handler_spec.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-api-pr-722

#724 (RST-6455) Updated site prism gem
  Gemfile
  Gemfile.lock
  spec/requests/v2/create_response_spec.rb
  spec/support/email_support/email_objects/new_response_email_html.rb
  spec/support/email_support/gov_uk_notify_email_objects/new_claim_email_en.rb
Labels: ns:et-pet, prd:et-pet, rel:et-pet-api-pr-724
